version: '3'
services:
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=auto
    ports:
      - "27017:27017"
    restart: on-failure
  auto-csv-parser:
    image: auto-csv-parser
    container_name: auto-csv-parser
    build: .
    ports:
      - "3001:3001"
    restart: on-failure
    depends_on:
      - mongo

